
language: python
python: 
  - "3.6" 

install: 
  - pip install -r requirement.txt
  - pip install coveralls

script:
  - cd ./reco
  - coverage --source=reco run ./test.py test

after_success:
  - coveralls