
language: python
python: 
  - "3.6" 

install: 
  - pip install -r requirement.txt
  - sh ./install.sh
  - pip3 list

script:
  - cd reco/test
  - sh test.sh
  - cd ..
  - cd reinforce
  - sh test.sh

after_success:
  - coveralls